window.All_Skills = [
  "PHP",
  "HTML",
  "JavaScript",
  "WordPress",
  "Software Architecture",
  "MySQL",
  "Python",
  "SEO",
  "Java",
  "C# Programming",
  "C Programming",
  "C++ Programming",
  "Node.js",
  "Linux",
  "Link Building",
  "React.js",
  "eCommerce",
  "HTML5",
  "Laravel",
  "Web Scraping",
  ".NET",
  "Flutter",
  "AngularJS",
  "Amazon Web Services",
  "Shopify",
  "Web Hosting",
  "Blockchain",
  "System Admin",
  "Twitter",
  "SQL",
  "Game Development",
  "Microsoft SQL Server",
  "Unity 3D",
  "Social Networking",
  "React Native",
  "Software Testing",
  "Visual Basic",
  "Web Security",
  "Network Administration",
  "Web Development",
  "Objective C",
  "User Interface / IA",
  "iOS Development",
  "ASP.NET",
  "YouTube",
  "Artificial Intelligence",
  "Computer Security",
  "Game Design",
  "Django",
  "Software Development",
  "Database Administration",
  "Digital Marketing",
  "Metatrader",
  "Swift",
  "Google Analytics",
  "Google Plus",
  "Instagram",
  "API",
  "jQuery / Prototype",
  "Windows Server",
  "Express JS",
  "Cryptocurrency",
  "MongoDB",
  "NoSQL Couch &amp; Mongo",
  "Ubuntu",
  "Coding",
  "Social Media Management",
  "Smart Contracts",
  "Cloud Computing",
  "Testing / QA",
  "Database Programming",
  "Internet Security",
  "Typescript",
  "Full Stack Development",
  "Backend Development",
  "Windows Desktop",
  "Website Testing",
  "Next.js",
  "Apache",
  "Microsoft",
  "Frontend Development",
  "Website Build",
  "Android App Development",
  "Magento",
  "Shopping Carts",
  "Codeigniter",
  "Google Firebase",
  "Microsoft Access",
  "Programming",
  "Website Management",
  "Linkedin",
  "Docker",
  "Vue.js",
  "RESTful API",
  "J2EE",
  "AWS Lambda",
  "Kubernetes",
  "Microsoft Azure",
  "Web3.js",
  "Test Automation",
  "Azure",
  "Pinterest",
  "R Programming Language",
  "Figma",
  "PostgreSQL",
  "VB.NET",
  "SPSS Statistics",
  "JSON",
  "Pine Script",
  "Non-fungible Tokens (NFT)",
  "Solidity",
  "Web Application",
  "AJAX",
  "Computer Science",
  "Angular",
  "Google Chrome",
  "Odoo",
  "A+ Certified IT Technician",
  "Elementor",
  "Visual Basic for Apps",
  "Git",
  "App Developer",
  "Cisco",
  "DNS",
  "Ethereum",
  "API Integration",
  "Spring Boot",
  "Joomla",
  "Google App Engine",
  "Adobe Premiere Pro",
  "Web Design",
  "Oracle",
  "Asterisk PBX",
  "Sharepoint",
  "Dart",
  "PhoneGap",
  "Database Development",
  "Data Collection",
  "XML",
  "Ruby on Rails",
  "Shell Script",
  "Prestashop",
  "Bitcoin",
  "Payment Gateway Integration",
  "Power BI",
  "React.js Framework",
  "Perl",
  "Drupal",
  "VoIP",
  "Nginx",
  "UNIX",
  "MVC",
  "Moodle",
  "Salesforce App Development",
  "Xamarin",
  "Google Sheets",
  "GitHub",
  "Unity",
  "Mac OS",
  "Microsoft Exchange",
  "Open Cart",
  "Mobile App Testing",
  "Ionic Framework",
  "Powershell",
  "Server",
  "jQuery",
  "Magento 2",
  "Android Studio",
  "Electronic Forms",
  "SAP",
  "Zoho",
  "Tableau",
  "Raspberry Pi",
  "Cinematography",
  "Selenium",
  "Development",
  "Certified Ethical Hacking",
  "Software Engineering",
  "Microsoft PowerBI",
  "WordPress Plugin",
  "Embedded Software",
  "Golang",
  "Google Maps API",
  "phpMyAdmin",
  "Electron JS",
  "JSP",
  "PayPal API",
  "Assembly",
  "Unreal Engine",
  "Blender",
  "Redux.js",
  "SSL",
  "Telegram API",
  "Amazon Listings Optimization",
  "Script Install",
  "Troubleshooting",
  "JavaFX",
  "Usability Testing",
  "Symfony PHP",
  "OCR",
  "x86/x64 Assembler",
  "Stripe",
  "Wix",
  "Documentation",
  "Office 365",
  ".NET Core",
  "Amazon FBA",
  "Power Automate",
  "Haskell",
  "Debugging",
  "Elasticsearch",
  "Facebook API",
  "Adobe Illustrator",
  "Java Spring",
  "Jenkins",
  "Web API",
  "Facebook Pixel",
  "Shopify Development",
  "Network Security",
  "GraphQL",
  "Chatbot",
  "Visual Studio",
  "NLP",
  "OpenGL",
  "Plugin",
  "Email Developer",
  "SEO Auditing",
  "Geographical Information System (GIS)",
  "Corel Draw",
  "Scripting",
  "Flask",
  "Google Cloud Platform",
  "GitLab",
  "Firmware",
  "Data Visualization",
  "Amibroker Formula Language",
  "Website Optimization",
  "Hubspot",
  "AWS Amplify",
  "Binance",
  "Terraform",
  "eLearning",
  "WHMCS",
  "Augmented Reality",
  "Sketching",
  "Qt",
  "Object Oriented Programming (OOP)",
  "Solutions Architecture",
  "Rust",
  "Bubble Developer",
  "Three.js",
  "PowerApps",
  "Automation",
  "IT Project Management",
  "Electronic Data Interchange (EDI)",
  "Zapier",
  "Adobe XD",
  "App Development",
  "Android SDK",
  "Zoho CRM",
  "MERN Stack",
  "Pandas",
  "CI/CD",
  "Active Directory",
  "FileMaker",
  "Plesk",
  "Hadoop",
  "Analytics",
  "Debian",
  "Spark",
  "OpenCV",
  "IT strategy",
  "Vue.js Framework",
  "Computer Vision",
  "ETL",
  "Webflow",
  "Google APIs",
  "Network Engineering",
  "MQL4",
  "API Development",
  "Robot Operating System (ROS)",
  "MetaTrader 4",
  "Binance Smart Chain",
  "Metatrader 5",
  "Progressive Web Apps",
  "White Hat SEO",
  "AR / VR 3D Asset",
  "ASP",
  "Prolog",
  "vTiger",
  "SugarCRM",
  "Socket IO",
  "Web Services",
  "RESTful",
  "Growth Hacking",
  "Bluetooth Low Energy (BLE)",
  "MQTT",
  "Squarespace",
  "Lua",
  "OpenSSL",
  "Twitter API",
  "Website Analytics",
  "Selenium Webdriver",
  "Apple Xcode",
  "CentOs",
  "Cloud",
  "Cloud Security",
  "Dynamic 365",
  "Zoho Creator",
  "Ansys",
  "Amazon Product Launch",
  "Point of Sale",
  "User Experience Research",
  "Docker Compose",
  "Desktop Application",
  "Micropython",
  "Tailwind CSS",
  "Google Apps Scripts",
  "UX Research",
  "SaaS",
  "UML Design",
  "Photoshop Coding",
  "OSCommerce",
  "CakePHP",
  "Dynamics",
  "Game Consoles",
  "Agile Development",
  "Big Data Sales",
  "VPS",
  "Scala",
  "Ruby",
  "Redis",
  "Data Warehousing",
  "OAuth",
  "Learning Management Systems (LMS)",
  "OpenVPN",
  "Virtual Machines",
  "Web Crawling",
  "Scrapy",
  "Charts",
  "ERP Software",
  "Google Tag Management",
  "Microsoft Project",
  "Prototyping",
  "Agile Project Management",
  "User Story Writing",
  "Architectural Engineering",
  "Ansible",
  "Apache Kafka",
  "VPN",
  "Big Data",
  "MERN",
  "AWS SageMaker",
  "Adobe Animate",
  "cPanel",
  "Google Search",
  "FastAPI",
  "Xcode",
  "Page Speed Optimization",
  "Cold Fusion",
  "CMS",
  "Forum Software",
  "Blog Install",
  "LabVIEW",
  "Firefox",
  "Apple Safari",
  "BigCommerce",
  "Google Web Toolkit",
  "Map Reduce",
  "Windows API",
  "XMPP",
  "VMware",
  "VoiceXML",
  "Zendesk",
  "Business Intelligence",
  "Visualization",
  "Bash Scripting",
  "SSIS (SQL Server Integration Services)",
  "Tensorflow",
  "Pytorch",
  "Revit Architecture",
  "Cloud Data",
  "Data Integration",
  "IT Operating Model",
  "Yii2",
  "Atlassian Jira",
  "AI/RPA development",
  "Digital Signal Processing",
  "ASP.NET MVC",
  "MEAN Stack",
  "Advanced Business Application Programming (ABAP)",
  "PySpark",
  "Financial Software Development",
  "Messenger Marketing",
  "Reverse Engineering",
  "Delphi",
  "MMORPG",
  "MySpace",
  "Erlang",
  "Volusion",
  "DotNetNuke",
  "Boonex Dolphin",
  "Social Engine",
  "Cocoa",
  "Google Wave",
  "Expression Engine",
  "Silverlight",
  "Zen Cart",
  "AS400 &amp; iSeries",
  "REALbasic",
  "IIS",
  "MODx",
  "vBulletin",
  "Zend",
  "Protoshare",
  "Balsamiq",
  "Microsoft Expression",
  "Virtual Worlds",
  "Chrome OS",
  "GPGPU",
  "BMC Remedy",
  "HP Openview",
  "Chordiant",
  "COBOL",
  "CUDA",
  "Fortran",
  "Google Buzz",
  "Apache Solr",
  "Pentaho",
  "Solaris",
  "Freelancer API",
  "XSLT",
  "PICK Multivalue DB",
  "Google Earth",
  "Virtuemart",
  "Sencha / YahooUI",
  "TaoBao API",
  "Business Catalyst",
  "IBM Tivoli",
  "CRE Loaded",
  "Visual Foxpro",
  "CubeCart",
  "Rocket Engine",
  "AutoHotkey",
  "Parallels Desktop",
  "Virtuozzo",
  "Parallels Automation",
  "Lotus Notes",
  "TestStand",
  "Kinect",
  "Smarty PHP",
  "Yii",
  "Interspire",
  "Face Recognition",
  "Pattern Matching",
  "Computer Graphics",
  "WPF",
  "Gamification",
  "DOS",
  "Google Checkout",
  "Ning",
  "Tumblr",
  "Scrum Development",
  "Grease Monkey",
  "CS-Cart",
  "webMethods",
  "OpenCL",
  "4D",
  "QlikView",
  "Siebel",
  "QuickBase",
  "Umbraco",
  "Biztalk",
  "Puppet",
  "Chef Configuration Management",
  "backbone.js",
  "Dthreejs",
  "Knockout.js",
  "Windows 8",
  "CasperJS",
  "BSD",
  "edX",
  "MariaDB",
  "Red Hat",
  "Jabber",
  "SQLite",
  "Google Webmaster Tools",
  "Lisp",
  "XQuery",
  "Scheme",
  "VertexFX",
  "Call Control XML",
  "TYPO3",
  "IBM Websphere Transformation Tool",
  "Qualtrics Survey Platform",
  "Argus Monitoring Software",
  "Sphinx",
  "Parallax Scrolling",
  "OpenVMS",
  "Scrum",
  "ITIL",
  "GameSalad",
  "Alibaba",
  "Adobe Air",
  "Snapchat",
  "Ember.js",
  "WatchKit",
  "Microsoft Hololens",
  "Binary Analysis",
  "MonetDB",
  "GoPro",
  "Heroku",
  "Grunt",
  "LESS/Sass/SCSS",
  "Hive",
  "HBase",
  "Yarn",
  "Cassandra",
  "Bower",
  "PencilBlue CMS",
  "Wufoo",
  "OpenBravo",
  "Vuforia",
  "Oculus Mobile SDK",
  "Google Cardboard",
  "Magic Leap",
  "Android Wear SDK",
  "Samsung Accessory SDK",
  "iBeacon",
  "Tizen SDK for Wearables",
  "Leap Motion SDK",
  "DDS",
  "AMQP",
  "Xoops",
  "Papiamento",
  "HomeKit",
  "Weebly",
  "Steam API",
  "Redshift",
  "CLIPS",
  "Tibco Spotfire",
  "Xojo",
  "DataLife Engine",
  "Minitab",
  "Paytrace",
  "FreeSwitch",
  "Applescript",
  "Apache Ant",
  "Google Cloud Storage",
  "LINQ",
  "OpenStack",
  "Regular Expressions",
  "Squid Cache",
  "Subversion",
  "Varnish Cache",
  "Splunk",
  "IBM BPM",
  "GIMP",
  "Veeam",
  "LiveCode",
  "Titanium",
  "RapidWeaver",
  "Tally Definition Language",
  "Adobe Captivate",
  "PEGA PRPC",
  "JD Edwards CNC",
  "Open Journal Systems",
  "XPages",
  "Storage Area Networks",
  "MeteorJS",
  "Grails",
  "Microsoft Visio",
  "OpenSceneGraph",
  "Ray-tracing",
  "Parallel Processing",
  "Oculus Rift",
  "HTC Vive",
  "Penetration Testing",
  "Asana",
  "Pardot Development",
  "Eclipse",
  "Copyright",
  "Swing (Java)",
  "cURL",
  "Camtasia",
  "Netbeans",
  "Pascal",
  "CV Library",
  "Adobe Muse",
  "JUnit",
  "CSS3",
  "Instagram API",
  "XHTML",
  "Assembla",
  "XAML",
  "Moz",
  "ADO.NET",
  "Apache Maven",
  "OpenVZ",
  "Adobe Pagemaker",
  "PhpNuke",
  "Graphics Programming",
  "phpFox",
  "Adobe Freehand",
  "ARKit",
  "ARCore",
  "jqGrid",
  "Push Notification",
  "BeautifulSoup",
  "Sails.js",
  "Vim",
  "F#",
  "Jinja2",
  "xpath",
  "Racket",
  "Datatables",
  "Dojo",
  "Lucene",
  "cxf",
  "CoffeeScript",
  "T-SQL (Transact Structures Query Language)",
  "IBM Bluemix",
  "XSS (Cross-site scripting)",
  "MapKit",
  "Scikit Learn",
  "Clojure",
  "Elixir",
  "Cocoa Touch",
  "VBScript",
  "Ext JS",
  "SVG",
  "ECMAScript",
  "Handlebars.js",
  "Julia Language",
  "Underscore.js",
  "RSS",
  "GTK+",
  "Java ME",
  "SCORM",
  "Enterprise Architecture",
  "Atlassian Confluence",
  "Articulate Storyline",
  "Apple UIKit",
  "Keras",
  "Development Operations",
  "Sketch",
  "Sass",
  "DOM",
  "HTTP",
  "RxJS",
  "NgRx",
  "Angular Material",
  "Karma Javascript",
  "Jasmine Javascript",
  "Protractor Javascript",
  "Fastlane",
  "CocoaPods",
  "Carthage",
  "Swift Package Manager",
  "Xcodebuild",
  "NoSQL",
  "Storm",
  "Heron",
  "Vapor",
  "Boost",
  "Travis CI",
  "TeamCity",
  "CircleCI",
  "ASM",
  "Version Control Git",
  "Prometheus Monitoring",
  "Soldering",
  "Armadillo",
  "LIBSVM",
  "FLANN",
  "NumPy",
  "SciPy",
  "Vowpal Wabbit",
  "Javascript ES6",
  "ES8 Javascript",
  "Revit",
  "iMacros",
  "Alteryx",
  "SDW N17 Service Qualification",
  "SAP Hybris",
  "Twilio",
  "VtrunkD",
  "SD-WAN",
  "IBM Tririga",
  "BIRT Development",
  "Data Modernization",
  "Open Source",
  "SAP Transformation",
  "ServiceNow",
  "IT Transformation",
  "Infor",
  "Time &amp; Labor SAP",
  "SAP Pay",
  "EC Pay Workday",
  "SAP 4 Hana",
  "SFDC",
  "Oracle Retail",
  "Cloud Finance",
  "Oracle EBS Tech Integration",
  "Guidewire",
  "CompTIA",
  "MuleSoft",
  "Java Technical Architecture",
  "Apttus",
  "NetSuite",
  "Anaplan",
  "Salesforce Marketing Cloud",
  "SAP BODS",
  "Data Governance",
  "Informatica Powercenter ETL",
  "Apache Hadoop",
  "Informatica MDM",
  "Oracle OBIA",
  "Oracle OBIEE",
  "SAP HANA",
  "SAP Business Planning and Consolidation",
  "Cloud Procurement",
  "Oracle Database",
  "Ariba",
  "Oracle Hyperion",
  "Cognos",
  "Znode",
  "PHP Slim",
  "Google PageSpeed Insights",
  "SAP PI",
  "SAP CPI",
  "Salesforce Commerce Cloud",
  "Julia Development",
  "HP-UX",
  "Hewlett Packard",
  "Local Area Networking",
  "Mobile Development",
  "Adobe Dynamic Tag Management",
  "Segment",
  "Tealium",
  "Facebook Product Catalog",
  "Facebook SDK",
  "Server to Server Facebook API Integration",
  "Offline Conversion Facebook API Integration",
  "Airtable",
  "TvOS",
  "Cocos2d",
  "V-Play",
  "WinJS",
  "KNIME",
  "PC Programming",
  "Genetic Algebra Modelling System",
  "Arena Simulation Programming",
  "Managed Analytics",
  "Test",
  "Amazon App Development",
  "Cloud Development",
  "Cloud Networking",
  "Dropbox API",
  "Certified Information Systems Security Professional (CISSP)",
  "Learning Management Solution (LMS) Consulting",
  "Highcharts",
  "Caspio",
  "LearnDash",
  "Kendo UI",
  "D3.js",
  "NAV",
  "Business Central",
  "Dynatrace Software Monitoring",
  "Application Performance Monitoring",
  "Oracle Primavera",
  "Xara",
  "Alexa Modification",
  "Google Docs",
  "Slack",
  "PostgreSQL Programming",
  "Amazon S3",
  "Roadnet",
  "A-GPS",
  "A/B Testing",
  "A+ Certified Professional",
  "Ab Initio",
  "ABAP Web Dynpro",
  "Abaqus",
  "ABIS",
  "AbleCommerce",
  "Ableton",
  "Ableton Live",
  "Ableton Push",
  "Ada programming",
  "AIX Administration",
  "AJAX Frameworks",
  "AJAX Toolkit",
  "Ajax4JSF",
  "Akka",
  "Alacra",
  "ALBPM",
  "Algorithm Analysis",
  "Alias",
  "Alibre Design",
  "Alienbrain",
  "All-Source Analysis",
  "AlphaCAM",
  "Altera Quartus",
  "ABAP List Viewer (ALV)",
  "Alvarion",
  "Automatic Number Plate Recognition (ANPR)",
  "AC3",
  "ACARS",
  "K2",
  "Polarion",
  "Redmine",
  "Hardware Security Module",
  "Keycloak",
  "Cloud Foundry",
  "National Building Specification",
  "Atmel",
  "BuddyPress",
  "Crestron",
  "Minecraft",
  "Roblox",
  "Facebook Development",
  "System Analysis",
  "SAP Screen Personas",
  "Micros RES",
  "OpenBSD",
  "IMAP",
  "POP / POP3",
  "Dovecot",
  "Postfix",
  "SMTP",
  "P2P Network",
  "Adobe Experience Manager",
  "MicroStrategy",
  "PHPrunner",
  "Office Add-ins",
  "HyperMesh",
  "Application Packaging",
  "Packaging Technology",
  "MOVEit",
  "IBM MQ",
  "IBM Integration bus",
  "IBM Datapower",
  "Oracle APEX",
  "Fusion 360",
  "Houdini",
  "IBM Cloud",
  "Buildbox",
  "Creo",
  "Geofencing",
  "COMPASS",
  "Jade Development",
  "RPG Development",
  "Technology Consulting",
  "Google Canvas",
  "FaunaDB",
  "ArangoDB",
  "GatsbyJS",
  "Jamstack",
  "Elm",
  "PureScript",
  "Svelte",
  "Reason",
  "Altium Designer",
  "Altium NEXUS",
  "CircuitStudio",
  "CircuitMaker",
  "ActiveCampaign",
  "MailerLite",
  "Funnel",
  "App Publication",
  "App Reskin",
  "RichFaces",
  "Low Code",
  "Appian BPM",
  "OctoberCMS",
  "Twitch",
  "Mininet",
  "Ryu Controller",
  "Udacity",
  "Arc",
  "Regression Testing",
  "Graylog",
  ".NET Core Web API",
  "Adobe Acrobat",
  "Espruino",
  "Puck.js",
  "Adobe Audition",
  "Adobe Creative Cloud",
  "Agora",
  "Affectiva",
  "Alpine JS",
  "ArchiCAD",
  "Forth",
  "AutoCAD Advance Steel",
  "ArcMap",
  "Aspen HYSYS",
  ".NET 5.0/6",
  "Blazor",
  "Windows Service",
  "Citadela",
  "JUCE",
  "BitMEX",
  "Cloudflare",
  "Fedora",
  "Data Modeling",
  "Predictive Analytics",
  "Apigee",
  "PCI Compliance",
  "BigQuery",
  "SIP",
  "Wrike",
  "Kibana",
  "Dynatrace",
  "Bioinformatics",
  "ArcGIS",
  "Data Management",
  "Biostatistics",
  "Jimdo",
  "Bash",
  "PLC",
  "Content Management System (CMS)",
  "TailWind",
  "Firewall",
  "Performance Tuning",
  "Mule",
  "Ubiquiti",
  "TradeStation",
  "Playstation VR",
  "Apollo",
  "Informatica",
  "Network Monitoring",
  "Scrivener",
  "Chromium",
  "Kajabi",
  "Avaya",
  "Teradata",
  "Braintree",
  "WebRTC",
  "Appfolio",
  "Data Backup",
  "HIPAA",
  "Formstack",
  "Hybris",
  "Apache Spark",
  "Algolia",
  "Backtesting",
  "Binary Search",
  "Cross Browser",
  "LAMP",
  "Clover",
  "Twago",
  "HFT",
  "PayPal",
  "Corda",
  "ADF / Oracle ADF",
  "Bukkit",
  "Quality Engineering",
  "FinTech",
  "DApps",
  "Juniper",
  "Celery",
  "Gulp.js",
  "Truffle",
  "RabbitMQ",
  "Litecoin",
  "Hyperledger",
  "Hyperledger Fabric",
  "Hugo",
  "Amazon ECS",
  "Nagios Core",
  "Citrix",
  "CSS2",
  "Angular 4",
  "Angular 6",
  "Nest.js",
  "Phoenix",
  "PHPUnit",
  "DigitalOcean",
  "Amazon CloudFront",
  "Jamf",
  "Amazon CloudFormation",
  "Linear Regression",
  "Cordana",
  "Solana",
  "Polkadot",
  "Ergo",
  "Algogrand",
  "Tether",
  "Terra",
  "DEMAT",
  "Dogecoin",
  "Etherscan",
  "GeoJSON",
  "Ionic React",
  "Jitsi",
  "Lottie",
  "Metamask",
  "Netlify",
  "OKTA",
  "OTT",
  "Proto",
  "Ratio Analysis",
  "Rebranding",
  "Roslyn",
  "Strapi",
  "Thermodynamics",
  "Tinkercad",
  "TRON",
  "Weblogic",
  "Wireguard",
  "WMS",
  "SurveyMonkey",
  "Powtoon",
  "Chart.js",
  "Bluebeam",
  "VideoHive",
  "FoxyCart",
  "Hybrid App",
  "Plivo",
  "Toon Boom",
  "Moho",
  "Lumion",
  "PyCaret",
  "AWS Translate",
  "AWS Textract",
  "AWS Polly",
  "GCP AI",
  "Background Removal",
  "Corteza",
  "Cloud Monitoring",
  "Website Localization",
  "App Localization",
  "WordPress Multilingual",
  "Draw.io",
  "GrooveFunnels",
  "Google Data Studio",
  "Monday.com",
  "Vulkan",
  "DirectX",
  "Metal",
  "Vymo",
  "Software Performance Testing",
  "API Testing",
  "JMeter",
  "Adobe Analytics",
  "Backbase",
  "WINDEV",
  "WEBDEV",
  "WINDEV Mobile",
  "Outreach.io",
  "CAN Bus",
  "BitMEX API",
  "Virtual Reality",
  "AutoML",
  "Construct 3",
  "GameMaker",
  "Phaser",
  "Godot",
  "PlayFab",
  "Photon Multiplayer",
  "Modding",
  "Editorial Design",
  "Fruugo",
  "Hibernate",
  "TopSolid",
  "TopSolid Wood",
  "Gravity Forms",
  "MyBB",
  "phpBB",
  "XenForo",
  "Spring Data",
  "Spring Security",
  "Spring JPA",
  "Keyshot",
  "Liquid Template",
  "Core PHP",
  "Zoom",
  "QR Code Making",
  "LIMS (Laboratory Information Management System)",
  "Yandex",
  "Baidu",
  "Quora",
  "Dapper",
  "GeoServer",
  "Graphical Network Simulator-3",
  "GTmetrix",
  "Cardano",
  "Plutus",
  "Magnolia",
  "System Administration",
  "SOAP API",
  "Unbounce",
  "Webpack",
  "Microsoft Graph",
  "Telerik",
  "REST API",
  "Razor Template Engine",
  "Quarkus",
  "PoseNet",
  "POS development",
  "Adobe Systems",
  "Google Systems",
  "Bitrix",
  "GoDaddy",
  "Process Simulation",
  "GPT-3",
  "OpenAI",
  "Distributed Systems",
  "Monkey C",
  "Garmin IQ",
  "OpenNMS",
  "CNC",
  "Stable Diffusion",
  "Dall-E",
  "DIALux",
  "Relux",
  "Oracle Analytics",
  "Snowflake",
  "Digital System Engineering",
];
